language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nose2 -v --with-coverage
  - coveralls
after_success:
  - coveralls
